project_id = "vojhptlreurutrzftatn"

[functions.auto-session]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-branded-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
