project_id = "vojhptlreurutrzftatn"

[functions.auto-session]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-branded-email]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.security-scan]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.passkey-auth]
verify_jwt = false
