import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText } from "lucide-react";

const StudentReports = () => (
  <DashboardLayout role="student">
    <div className="space-y-6">
      <h1 className="font-display text-2xl font-bold text-foreground">Report Cards</h1>
      <Card>
        <CardHeader><CardTitle className="flex items-center gap-2"><FileText className="w-5 h-5" /> My Report Cards</CardTitle></CardHeader>
        <CardContent>
          <p className="text-muted-foreground">Your report cards will appear here once they are generated by your teachers at the end of each term.</p>
        </CardContent>
      </Card>
    </div>
  </DashboardLayout>
);

export default StudentReports;
